name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
      - sporacid/changes-for-engine
permissions:
  contents: write
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Dependencies
        run: |
          sudo apt-get -qq update &&
          sudo apt-get install -y build-essential llvm clang libclang-dev libtbb-dev ninja-build jq &&
          jq '.registries[0].packages += ["llvm"]' vcpkg-configuration.json > vcpkg-configuration.json.tmp &&
          mv vcpkg-configuration.json.tmp vcpkg-configuration.json
      - uses: lukka/get-cmake@latest
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'c95000e1b5bb62884de08d5e952993c8bced9db6'
      - name: Run CMake consuming CMakePreset.json and run vcpkg to build dependencies
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-vcpkg'
          buildPreset: 'ninja-vcpkg-release'
          testPreset: 'ninja-vcpkg-test-release'
        env:
          CC: clang
          CXX: clang++
      # - name: Setup Dependencies
      #   run: |
      #     sudo apt-get -qq update &&
      #     sudo apt-get install -y llvm clang libclang-dev libtbb-dev ninja-build
      # - name: Configure CMake Project
      #   run: cmake -B.cmake -G 'Ninja'
      # - name: Build CMake Project
      #   run: cmake --build .cmake --config Release
      # - name: Test CMake Project
      #   run: ctest --test-dir .cmake/tests --no-tests=error --output-on-failure --verbose
      - name: Tag Version
        if: github.ref == 'refs/heads/main'
        run: |
          GIT_TAG="v$(cat .cmake/CMakeCache.txt | awk -F= '$1~/CMAKE_PROJECT_VERSION:STATIC/{print$2}')" &&
          git config user.name "${GITHUB_ACTOR}" &&
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" &&
          git tag -af $GIT_TAG -m "Auto-generated semantic tag $GIT_TAG" &&
          git push origin $GIT_TAG --force
