name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: |
          sudo apt-get -qq update &&
          sudo apt-get install -y build-essential libtbb-dev ninja-build jq &&
          jq '.registries[0].packages += ["llvm"]' vcpkg-configuration.json > vcpkg-configuration.json.tmp &&
          mv vcpkg-configuration.json.tmp vcpkg-configuration.json
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "17.0"
      - name: Install CMake
        uses: lukka/get-cmake@latest
      - name: Install Vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '8eb57355a4ffb410a2e94c07b4dca2dffbee8e50'
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-vcpkg'
          buildPreset: 'ninja-vcpkg-release'
          testPreset: 'ninja-vcpkg-test-release'
          testPresetAdditionalArgs: "['--no-tests=error','--output-on-failure','--verbose']"
      - name: Tag Version
        if: github.ref == 'refs/heads/main'
        run: |
          VERSION=$(bash .github/scripts/get_version.sh) &&
          git config user.name "${GITHUB_ACTOR}" &&
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" &&
          $(echo $GIT_TAG > VERSION) &&
          git commit -m "chore: Update VERSION" &&
          git tag -af v$VERSION -m "Auto-generated semantic tag v$VERSION" &&
          git push origin $GIT_TAG --force
